/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as UserRouteRouteImport } from './routes/_user/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as OauthConsentRouteImport } from './routes/oauth/consent'
import { Route as UserSubmitFriendLinkRouteImport } from './routes/_user/submit-friend-link'
import { Route as UserProfileRouteImport } from './routes/_user/profile'
import { Route as PublicUnsubscribeRouteImport } from './routes/_public/unsubscribe'
import { Route as PublicSearchRouteImport } from './routes/_public/search'
import { Route as PublicHomeRouteImport } from './routes/_public/home'
import { Route as PublicFriendLinksRouteImport } from './routes/_public/friend-links'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth/verify-email'
import { Route as AuthResetLinkRouteImport } from './routes/_auth/reset-link'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AdminPostsRouteRouteImport } from './routes/admin/posts/route'
import { Route as PublicNavSlugRouteRouteImport } from './routes/_public/$navSlug/route'
import { Route as AdminTagsIndexRouteImport } from './routes/admin/tags/index'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminPostsIndexRouteImport } from './routes/admin/posts/index'
import { Route as AdminMediaIndexRouteImport } from './routes/admin/media/index'
import { Route as AdminFriendLinksIndexRouteImport } from './routes/admin/friend-links/index'
import { Route as AdminCommentsIndexRouteImport } from './routes/admin/comments/index'
import { Route as PublicPostsIndexRouteImport } from './routes/_public/posts/index'
import { Route as PublicNavSlugIndexRouteImport } from './routes/_public/$navSlug/index'
import { Route as PublicPostsSlugRouteImport } from './routes/_public/posts/$slug'
import { Route as PublicNavSlugPostSlugRouteImport } from './routes/_public/$navSlug/$postSlug'
import { Route as PublicNavNavIdRouteRouteImport } from './routes/_public/nav/$navId/route'
import { Route as PublicNavNavIdIndexRouteImport } from './routes/_public/nav/$navId/index'
import { Route as AdminPostsEditIdRouteImport } from './routes/admin/posts/edit.$id'
import { Route as PublicNavNavIdPostSlugRouteImport } from './routes/_public/nav/$navId/$postSlug'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRouteRoute = UserRouteRouteImport.update({
  id: '/_user',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const UserSubmitFriendLinkRoute = UserSubmitFriendLinkRouteImport.update({
  id: '/submit-friend-link',
  path: '/submit-friend-link',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserProfileRoute = UserProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => UserRouteRoute,
} as any)
const PublicUnsubscribeRoute = PublicUnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicSearchRoute = PublicSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicHomeRoute = PublicHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicFriendLinksRoute = PublicFriendLinksRouteImport.update({
  id: '/friend-links',
  path: '/friend-links',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetLinkRoute = AuthResetLinkRouteImport.update({
  id: '/reset-link',
  path: '/reset-link',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AdminPostsRouteRoute = AdminPostsRouteRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PublicNavSlugRouteRoute = PublicNavSlugRouteRouteImport.update({
  id: '/$navSlug',
  path: '/$navSlug',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AdminTagsIndexRoute = AdminTagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPostsIndexRoute = AdminPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPostsRouteRoute,
} as any)
const AdminMediaIndexRoute = AdminMediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFriendLinksIndexRoute = AdminFriendLinksIndexRouteImport.update({
  id: '/friend-links/',
  path: '/friend-links/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCommentsIndexRoute = AdminCommentsIndexRouteImport.update({
  id: '/comments/',
  path: '/comments/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PublicPostsIndexRoute = PublicPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicNavSlugIndexRoute = PublicNavSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicNavSlugRouteRoute,
} as any)
const PublicPostsSlugRoute = PublicPostsSlugRouteImport.update({
  id: '/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicNavSlugPostSlugRoute = PublicNavSlugPostSlugRouteImport.update({
  id: '/$postSlug',
  path: '/$postSlug',
  getParentRoute: () => PublicNavSlugRouteRoute,
} as any)
const PublicNavNavIdRouteRoute = PublicNavNavIdRouteRouteImport.update({
  id: '/nav/$navId',
  path: '/nav/$navId',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicNavNavIdIndexRoute = PublicNavNavIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicNavNavIdRouteRoute,
} as any)
const AdminPostsEditIdRoute = AdminPostsEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AdminPostsRouteRoute,
} as any)
const PublicNavNavIdPostSlugRoute = PublicNavNavIdPostSlugRouteImport.update({
  id: '/$postSlug',
  path: '/$postSlug',
  getParentRoute: () => PublicNavNavIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/$navSlug': typeof PublicNavSlugRouteRouteWithChildren
  '/admin/posts': typeof AdminPostsRouteRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-link': typeof AuthResetLinkRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/friend-links': typeof PublicFriendLinksRoute
  '/home': typeof PublicHomeRoute
  '/search': typeof PublicSearchRoute
  '/unsubscribe': typeof PublicUnsubscribeRoute
  '/profile': typeof UserProfileRoute
  '/submit-friend-link': typeof UserSubmitFriendLinkRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/admin/': typeof AdminIndexRoute
  '/nav/$navId': typeof PublicNavNavIdRouteRouteWithChildren
  '/$navSlug/$postSlug': typeof PublicNavSlugPostSlugRoute
  '/posts/$slug': typeof PublicPostsSlugRoute
  '/$navSlug/': typeof PublicNavSlugIndexRoute
  '/posts/': typeof PublicPostsIndexRoute
  '/admin/comments/': typeof AdminCommentsIndexRoute
  '/admin/friend-links/': typeof AdminFriendLinksIndexRoute
  '/admin/media/': typeof AdminMediaIndexRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/tags/': typeof AdminTagsIndexRoute
  '/nav/$navId/$postSlug': typeof PublicNavNavIdPostSlugRoute
  '/admin/posts/edit/$id': typeof AdminPostsEditIdRoute
  '/nav/$navId/': typeof PublicNavNavIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-link': typeof AuthResetLinkRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/friend-links': typeof PublicFriendLinksRoute
  '/home': typeof PublicHomeRoute
  '/search': typeof PublicSearchRoute
  '/unsubscribe': typeof PublicUnsubscribeRoute
  '/profile': typeof UserProfileRoute
  '/submit-friend-link': typeof UserSubmitFriendLinkRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/admin': typeof AdminIndexRoute
  '/$navSlug/$postSlug': typeof PublicNavSlugPostSlugRoute
  '/posts/$slug': typeof PublicPostsSlugRoute
  '/$navSlug': typeof PublicNavSlugIndexRoute
  '/posts': typeof PublicPostsIndexRoute
  '/admin/comments': typeof AdminCommentsIndexRoute
  '/admin/friend-links': typeof AdminFriendLinksIndexRoute
  '/admin/media': typeof AdminMediaIndexRoute
  '/admin/posts': typeof AdminPostsIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/tags': typeof AdminTagsIndexRoute
  '/nav/$navId/$postSlug': typeof PublicNavNavIdPostSlugRoute
  '/admin/posts/edit/$id': typeof AdminPostsEditIdRoute
  '/nav/$navId': typeof PublicNavNavIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_user': typeof UserRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/_public/$navSlug': typeof PublicNavSlugRouteRouteWithChildren
  '/admin/posts': typeof AdminPostsRouteRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-link': typeof AuthResetLinkRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_public/friend-links': typeof PublicFriendLinksRoute
  '/_public/home': typeof PublicHomeRoute
  '/_public/search': typeof PublicSearchRoute
  '/_public/unsubscribe': typeof PublicUnsubscribeRoute
  '/_user/profile': typeof UserProfileRoute
  '/_user/submit-friend-link': typeof UserSubmitFriendLinkRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/admin/': typeof AdminIndexRoute
  '/_public/nav/$navId': typeof PublicNavNavIdRouteRouteWithChildren
  '/_public/$navSlug/$postSlug': typeof PublicNavSlugPostSlugRoute
  '/_public/posts/$slug': typeof PublicPostsSlugRoute
  '/_public/$navSlug/': typeof PublicNavSlugIndexRoute
  '/_public/posts/': typeof PublicPostsIndexRoute
  '/admin/comments/': typeof AdminCommentsIndexRoute
  '/admin/friend-links/': typeof AdminFriendLinksIndexRoute
  '/admin/media/': typeof AdminMediaIndexRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/tags/': typeof AdminTagsIndexRoute
  '/_public/nav/$navId/$postSlug': typeof PublicNavNavIdPostSlugRoute
  '/admin/posts/edit/$id': typeof AdminPostsEditIdRoute
  '/_public/nav/$navId/': typeof PublicNavNavIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/$navSlug'
    | '/admin/posts'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-link'
    | '/verify-email'
    | '/friend-links'
    | '/home'
    | '/search'
    | '/unsubscribe'
    | '/profile'
    | '/submit-friend-link'
    | '/oauth/consent'
    | '/admin/'
    | '/nav/$navId'
    | '/$navSlug/$postSlug'
    | '/posts/$slug'
    | '/$navSlug/'
    | '/posts/'
    | '/admin/comments/'
    | '/admin/friend-links/'
    | '/admin/media/'
    | '/admin/posts/'
    | '/admin/settings/'
    | '/admin/tags/'
    | '/nav/$navId/$postSlug'
    | '/admin/posts/edit/$id'
    | '/nav/$navId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-link'
    | '/verify-email'
    | '/friend-links'
    | '/home'
    | '/search'
    | '/unsubscribe'
    | '/profile'
    | '/submit-friend-link'
    | '/oauth/consent'
    | '/admin'
    | '/$navSlug/$postSlug'
    | '/posts/$slug'
    | '/$navSlug'
    | '/posts'
    | '/admin/comments'
    | '/admin/friend-links'
    | '/admin/media'
    | '/admin/posts'
    | '/admin/settings'
    | '/admin/tags'
    | '/nav/$navId/$postSlug'
    | '/admin/posts/edit/$id'
    | '/nav/$navId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_public'
    | '/_user'
    | '/admin'
    | '/_public/$navSlug'
    | '/admin/posts'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-link'
    | '/_auth/verify-email'
    | '/_public/friend-links'
    | '/_public/home'
    | '/_public/search'
    | '/_public/unsubscribe'
    | '/_user/profile'
    | '/_user/submit-friend-link'
    | '/oauth/consent'
    | '/admin/'
    | '/_public/nav/$navId'
    | '/_public/$navSlug/$postSlug'
    | '/_public/posts/$slug'
    | '/_public/$navSlug/'
    | '/_public/posts/'
    | '/admin/comments/'
    | '/admin/friend-links/'
    | '/admin/media/'
    | '/admin/posts/'
    | '/admin/settings/'
    | '/admin/tags/'
    | '/_public/nav/$navId/$postSlug'
    | '/admin/posts/edit/$id'
    | '/_public/nav/$navId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  UserRouteRoute: typeof UserRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  OauthConsentRoute: typeof OauthConsentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user': {
      id: '/_user'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UserRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user/submit-friend-link': {
      id: '/_user/submit-friend-link'
      path: '/submit-friend-link'
      fullPath: '/submit-friend-link'
      preLoaderRoute: typeof UserSubmitFriendLinkRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_user/profile': {
      id: '/_user/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_public/unsubscribe': {
      id: '/_public/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof PublicUnsubscribeRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/search': {
      id: '/_public/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof PublicSearchRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/home': {
      id: '/_public/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof PublicHomeRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/friend-links': {
      id: '/_public/friend-links'
      path: '/friend-links'
      fullPath: '/friend-links'
      preLoaderRoute: typeof PublicFriendLinksRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reset-link': {
      id: '/_auth/reset-link'
      path: '/reset-link'
      fullPath: '/reset-link'
      preLoaderRoute: typeof AuthResetLinkRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/$navSlug': {
      id: '/_public/$navSlug'
      path: '/$navSlug'
      fullPath: '/$navSlug'
      preLoaderRoute: typeof PublicNavSlugRouteRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/admin/tags/': {
      id: '/admin/tags/'
      path: '/tags'
      fullPath: '/admin/tags/'
      preLoaderRoute: typeof AdminTagsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/posts/': {
      id: '/admin/posts/'
      path: '/'
      fullPath: '/admin/posts/'
      preLoaderRoute: typeof AdminPostsIndexRouteImport
      parentRoute: typeof AdminPostsRouteRoute
    }
    '/admin/media/': {
      id: '/admin/media/'
      path: '/media'
      fullPath: '/admin/media/'
      preLoaderRoute: typeof AdminMediaIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/friend-links/': {
      id: '/admin/friend-links/'
      path: '/friend-links'
      fullPath: '/admin/friend-links/'
      preLoaderRoute: typeof AdminFriendLinksIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/comments/': {
      id: '/admin/comments/'
      path: '/comments'
      fullPath: '/admin/comments/'
      preLoaderRoute: typeof AdminCommentsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/posts/': {
      id: '/_public/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof PublicPostsIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/$navSlug/': {
      id: '/_public/$navSlug/'
      path: '/'
      fullPath: '/$navSlug/'
      preLoaderRoute: typeof PublicNavSlugIndexRouteImport
      parentRoute: typeof PublicNavSlugRouteRoute
    }
    '/_public/posts/$slug': {
      id: '/_public/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof PublicPostsSlugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/$navSlug/$postSlug': {
      id: '/_public/$navSlug/$postSlug'
      path: '/$postSlug'
      fullPath: '/$navSlug/$postSlug'
      preLoaderRoute: typeof PublicNavSlugPostSlugRouteImport
      parentRoute: typeof PublicNavSlugRouteRoute
    }
    '/_public/nav/$navId': {
      id: '/_public/nav/$navId'
      path: '/nav/$navId'
      fullPath: '/nav/$navId'
      preLoaderRoute: typeof PublicNavNavIdRouteRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/nav/$navId/': {
      id: '/_public/nav/$navId/'
      path: '/'
      fullPath: '/nav/$navId/'
      preLoaderRoute: typeof PublicNavNavIdIndexRouteImport
      parentRoute: typeof PublicNavNavIdRouteRoute
    }
    '/admin/posts/edit/$id': {
      id: '/admin/posts/edit/$id'
      path: '/edit/$id'
      fullPath: '/admin/posts/edit/$id'
      preLoaderRoute: typeof AdminPostsEditIdRouteImport
      parentRoute: typeof AdminPostsRouteRoute
    }
    '/_public/nav/$navId/$postSlug': {
      id: '/_public/nav/$navId/$postSlug'
      path: '/$postSlug'
      fullPath: '/nav/$navId/$postSlug'
      preLoaderRoute: typeof PublicNavNavIdPostSlugRouteImport
      parentRoute: typeof PublicNavNavIdRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetLinkRoute: typeof AuthResetLinkRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetLinkRoute: AuthResetLinkRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface PublicNavSlugRouteRouteChildren {
  PublicNavSlugPostSlugRoute: typeof PublicNavSlugPostSlugRoute
  PublicNavSlugIndexRoute: typeof PublicNavSlugIndexRoute
}

const PublicNavSlugRouteRouteChildren: PublicNavSlugRouteRouteChildren = {
  PublicNavSlugPostSlugRoute: PublicNavSlugPostSlugRoute,
  PublicNavSlugIndexRoute: PublicNavSlugIndexRoute,
}

const PublicNavSlugRouteRouteWithChildren =
  PublicNavSlugRouteRoute._addFileChildren(PublicNavSlugRouteRouteChildren)

interface PublicNavNavIdRouteRouteChildren {
  PublicNavNavIdPostSlugRoute: typeof PublicNavNavIdPostSlugRoute
  PublicNavNavIdIndexRoute: typeof PublicNavNavIdIndexRoute
}

const PublicNavNavIdRouteRouteChildren: PublicNavNavIdRouteRouteChildren = {
  PublicNavNavIdPostSlugRoute: PublicNavNavIdPostSlugRoute,
  PublicNavNavIdIndexRoute: PublicNavNavIdIndexRoute,
}

const PublicNavNavIdRouteRouteWithChildren =
  PublicNavNavIdRouteRoute._addFileChildren(PublicNavNavIdRouteRouteChildren)

interface PublicRouteRouteChildren {
  PublicNavSlugRouteRoute: typeof PublicNavSlugRouteRouteWithChildren
  PublicFriendLinksRoute: typeof PublicFriendLinksRoute
  PublicHomeRoute: typeof PublicHomeRoute
  PublicSearchRoute: typeof PublicSearchRoute
  PublicUnsubscribeRoute: typeof PublicUnsubscribeRoute
  PublicNavNavIdRouteRoute: typeof PublicNavNavIdRouteRouteWithChildren
  PublicPostsSlugRoute: typeof PublicPostsSlugRoute
  PublicPostsIndexRoute: typeof PublicPostsIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicNavSlugRouteRoute: PublicNavSlugRouteRouteWithChildren,
  PublicFriendLinksRoute: PublicFriendLinksRoute,
  PublicHomeRoute: PublicHomeRoute,
  PublicSearchRoute: PublicSearchRoute,
  PublicUnsubscribeRoute: PublicUnsubscribeRoute,
  PublicNavNavIdRouteRoute: PublicNavNavIdRouteRouteWithChildren,
  PublicPostsSlugRoute: PublicPostsSlugRoute,
  PublicPostsIndexRoute: PublicPostsIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface UserRouteRouteChildren {
  UserProfileRoute: typeof UserProfileRoute
  UserSubmitFriendLinkRoute: typeof UserSubmitFriendLinkRoute
}

const UserRouteRouteChildren: UserRouteRouteChildren = {
  UserProfileRoute: UserProfileRoute,
  UserSubmitFriendLinkRoute: UserSubmitFriendLinkRoute,
}

const UserRouteRouteWithChildren = UserRouteRoute._addFileChildren(
  UserRouteRouteChildren,
)

interface AdminPostsRouteRouteChildren {
  AdminPostsIndexRoute: typeof AdminPostsIndexRoute
  AdminPostsEditIdRoute: typeof AdminPostsEditIdRoute
}

const AdminPostsRouteRouteChildren: AdminPostsRouteRouteChildren = {
  AdminPostsIndexRoute: AdminPostsIndexRoute,
  AdminPostsEditIdRoute: AdminPostsEditIdRoute,
}

const AdminPostsRouteRouteWithChildren = AdminPostsRouteRoute._addFileChildren(
  AdminPostsRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminPostsRouteRoute: typeof AdminPostsRouteRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCommentsIndexRoute: typeof AdminCommentsIndexRoute
  AdminFriendLinksIndexRoute: typeof AdminFriendLinksIndexRoute
  AdminMediaIndexRoute: typeof AdminMediaIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  AdminTagsIndexRoute: typeof AdminTagsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminPostsRouteRoute: AdminPostsRouteRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminCommentsIndexRoute: AdminCommentsIndexRoute,
  AdminFriendLinksIndexRoute: AdminFriendLinksIndexRoute,
  AdminMediaIndexRoute: AdminMediaIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminTagsIndexRoute: AdminTagsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  UserRouteRoute: UserRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  OauthConsentRoute: OauthConsentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
